#ifndef CONFIG_H
#define CONFIG_H

#define CALL_ID_LENGTH 32
#define USER_ID_LENGTH 32

#define MAX_STATUS_LENGTH 200

#define MESSAGE_ID_LENGTH 32
#define MAX_CONTENT_LENGTH 1024
#define MAX_BULK_MESSAGES 100

#define CONTACT_ID_LENGTH 32

#define MAX_CONTACT_NAME_LENGTH 100
#define MAX_CONTACT_ID_LENGTH 32

#define MAX_CONVERSATION_ID_LENGTH 32
#define MAX_CONVERSATION_NAME_LENGTH 100
#define MAX_LAST_MESSAGE_PREVIEW_LENGTH 50

#endif //CONFIG_H
